#!/usr/bin/env bash

set -e

# Base Config
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Dotbot config profiles
CONFIG_DIR="dotbot-configs"
CONFIG_SUFFIX=".yaml"
CONFIG_DEFAULT="default"

# Dotbot plugins
PLUGIN_DIR="dotbot-plugins"
PLUGIN_OS="dotbot-eopkg"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# If the --no-default option is used omit the default config
if [ "$1" != "--no-default" ]; then
	export ENV_LIST=(${CONFIG_DEFAULT} "${@}")
else
	shift
	export ENV_LIST=("${@}")
fi

for conf in "${ENV_LIST[@]}"; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${PLUGIN_DIR}/${PLUGIN_OS}" -c "${CONFIG_DIR}/${conf}${CONFIG_SUFFIX}"
done
